# -*- coding: utf-8 -*-
"""Desenv Agente LOGICAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSF-mKqDUjVzlGeZgh_eGfh9FZGtOvjU
"""

# Instalação das bibliotecas
!pip install langchain pypdf sentence-transformers chromadb langchain-community

#!pip install google-generativeai PyPDF2 python-dotenv

from google.colab import userdata
GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# 1. Carregar o PDF
loader = PyPDFLoader("dados_logicar.pdf")
documentos = loader.load()


text_splitter = RecursiveCharacterTextSplitter (
    chunk_size=500,
    chunk_overlap=50
)

chunks = text_splitter.split_documents(documentos)

print(f"Documento carregado com sucesso!")
print(f"Total de pedaços: {len(chunks)}")

#!pip install -U langchain-google-genai chromadb

import google.generativeai as genai

genai.configure(api_key=GEMINI_API_KEY)

from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_community.vectorstores import Chroma
from langchain_classic.chains import RetrievalQA

minha_api_key = GEMINI_API_KEY

# 1. Configurar os Embeddings (essencial para o RAG encontrar os textos no PDF)
embeddings = GoogleGenerativeAIEmbeddings(
    model="models/gemini-embedding-2",
    google_api_key=minha_api_key
)

# 2. Criar o Banco de Dados com os 'chunks' do seu PDF da Soluções Logicar
vectorstore = Chroma.from_documents(
    documents=chunks,
    embedding=embeddings
)

# 3. Configurar o LLM usando o modelo que funcionou no seu teste!
llm = ChatGoogleGenerativeAI(
    model="gemini-flash-latest",
    google_api_key=minha_api_key,
    temperature=0
)

# 4. Criar o Agente de Respostas
agente_logicar = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectorstore.as_retriever()
)

print("✅ Agente Soluções Logicar ONLINE com o modelo Flash-Latest!")

"""#Testando o Agente"""

pergunta = "De acordo com o manual, o que acontece se uma entrega de logística atrasar?"
try:
    resultado = agente_logicar.invoke(pergunta)
    print(f"RESPOSTA DO AGENTE: {resultado['result']}")
except Exception as e:
    print(f"Erro no teste: {e}")
